name: Build and Push to Artifact Registry and run on cloud run job

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: big-formula-457308-s5
  REGION: europe-west1
  GAR_LOCATION: europe-west1-docker.pkg.dev/big-formula-457308-s5/classify-bot-repo/classifybot-image

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}

      - name: Push Docker image
        run: docker push ${{ env.GAR_LOCATION }}

      - name: Deploy Cloud Run Job
        run: |
          JOB_NAME=discord-bot-job
          IMAGE=${{ env.GAR_LOCATION }}

          # Check if the job exists
          if gcloud run jobs describe $JOB_NAME --region=${{ env.REGION }} --format="value(name)" 2>/dev/null; then
            echo "Job exists. Updating..."
            gcloud run jobs update $JOB_NAME \
              --image $IMAGE \
              --region=${{ env.REGION }} \
              --set-secrets DISCORD_TOKEN=DISCORD_TOKEN:latest
          else
            echo "Creating new Cloud Run Job..."
            gcloud run jobs create $JOB_NAME \
              --image $IMAGE \
              --region=${{ env.REGION }} \
              --memory 512Mi \
              --timeout 900s \
              --set-secrets DISCORD_TOKEN=DISCORD_TOKEN:latest
          fi
