name: Deploy Discord Bot to Cloud Run from Artifact registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: big-formula-457308-s5
          service_account_email: sa-github-actions@big-formula-457308-s5.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Validate GCP authentication
        run: |
          gcloud auth list
          gcloud projects describe big-formula-457308-s5

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/big-formula-457308-s5/classify-bot-repo/discord-bot:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west1-docker.pkg.dev/big-formula-457308-s5/classify-bot-repo/discord-bot:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy discord-bot \
            --image europe-west1-docker.pkg.dev/big-formula-457308-s5/classify-bot-repo/discord-bot:$GITHUB_SHA \
            --platform managed \
            --region europe-west1 \
            --memory 512Mi \
            --timeout 300s \
            --set-secrets DISCORD_TOKEN=DISCORD_TOKEN:latest \
            --allow-unauthenticated
